name: colony-cdapp-dev-env
services:
  network-contracts:
    container_name: 'network'
    image: colony-cdapp-dev-env/network:latest
    volumes:
      - '../amplify/mock-data:/colonyCDapp/amplify/mock-data'
    network_mode: 'host'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002"]
      interval: 5s
      retries: 36
  reputation-monitor:
    container_name: 'monitor'
    image: colony-cdapp-dev-env/reputation-monitor:latest
    volumes:
      - '../amplify/mock-data:/colonyCDapp/amplify/mock-data'
    network_mode: 'host'
    depends_on:
      network-contracts:
        condition: service_healthy
  block-ingestor:
    container_name: 'ingestor'
    image: colony-cdapp-dev-env/block-ingestor:latest
    volumes:
      - '../amplify/mock-data:/colonyCDapp/amplify/mock-data'
    network_mode: 'host'
    depends_on:
      network-contracts:
        condition: service_healthy
  amplify:
    container_name: 'amplify'
    image: colony-cdapp-dev-env/amplify:latest
    volumes:
      - '../amplify/backend:/colonyCDapp/amplify/backend'
      - '../amplify/mock-data:/colonyCDapp/amplify/mock-data'
      - '../src/graphql:/colonyCDapp/src/graphql'
    network_mode: 'host'
    depends_on:
      network-contracts:
        condition: service_healthy
